title: miplaneta.com Apps & Services Status Page
languageCode: es
params:
  copyrightHolder: miplaneta.com
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description_footer: ''
  description_header: >-
    Information about <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.example.com/'>example</a> systems operations.<br />Follow
    us <a class='text-grey-darkest' title='Visit our page on Twitter'
    href='https://www.twitter.com/example'>on Twitter</a> or subscribe to <a
    class='text-grey-darkest' href='%s' >RSS</a><br />to be alerted of new
    events.
  eventsPerPage: 10
  groups:
    - Apps
  logo: >-
    http://www.miplaneta.com/wp1/wp-content/uploads/2017/02/logo-1-uai-1032x258.png
  meta_description: ''
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Mobile Apps published on Play Store and App Store
      link: ''
      name: Apps
  timezoneString: ' UTC'
